server:
  port: 8080
  servlet:
    context-path: /tingting
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tingting-dev.cdzu7yawx9hf.ap-northeast-1.rds.amazonaws.com:3306/tingting?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: tingting
    password: "!Q2w3e4r5t6y"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 587
    username: "tingting7777@naver.com"
    password: "!Q2w3e4r5t6y"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000